export const tanks = [
//Start of Harlequin Tanks 
  {
    tankId: 1,
    name: 'Harlequin 350HQi',
    brand: 'Harlequin',
    price: 780,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_350_2048x2048.jpg?v=1578329635',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_350_2048x2048.jpg?v=1578329635',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4394263314498',
    physicalprops:   {volume: 350,
                  brimfulVolume: '358',
                  height: 116,
                  length: 98,
                  width: 98,
                  weight: 45,
                  shapeType: '',
                  internalShape: 'vertical cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: '', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Installation:  cement base 158 x 158 cm',
                      misc2: '',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 2,
    name: 'Harlequin 650HQi',
    brand: 'Harlequin',
    price: 1054.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_650_2048x2048.jpg?v=1578342030',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_650_2048x2048.jpg?v=1578342030',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424748433474',
    physicalprops:   {volume: 650,
                  brimfulVolume: '673',
                  height: 133,
                  length: 171.5,
                  width: 67,
                  weight: 116,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Installation:  cement base 231.5 x 127 cm',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 3,
    name: 'Harlequin 1000HQi',
    brand: 'Harlequin',
    price: 1234.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1000_2048x2048.jpg?v=1578343212',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1000_2048x2048.jpg?v=1578343212',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424767209538',
    physicalprops:   {volume: 1000,
                  brimfulVolume: 1055,
                  height: 142,
                  length: 215,
                  width: 69,
                  weight: 132,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 275 x 131 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 4,
    name: 'Harlequin 1100HQi',
    brand: 'Harlequin',
    price: 1234.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1100_2048x2048.jpg?v=1578343605',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1100_2048x2048.jpg?v=1578343605',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424772616258',
    physicalprops:   {volume: 1100,
                  brimfulVolume: 1097,
                  height: 159.5,
                  length: 188,
                  width: 89,
                  weight: 132,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 248 x 149 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 5,
    name: 'Harlequin 1200HQi',
    brand: 'Harlequin',
    price: 1318.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1200_2048x2048.jpg?v=1578344171',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1200_2048x2048.jpg?v=1578344171',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424778383426',
    physicalprops:   {volume: 1200,
                  brimfulVolume: 1317,
                  height: 96,
                  length: 190,
                  width: 160,
                  weight: 130,
                  shapeType: 'low profile',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 250 x 220 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 6,
    name: 'Harlequin 1225HQi',
    brand: 'Harlequin',
    price: 1306.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1225_2048x2048.jpg?v=1578345079',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1225_2048x2048.jpg?v=1578345079',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424791195714',
    physicalprops:   {volume: 1225,
                  brimfulVolume: 1248,
                  height: 152.5,
                  length: 211,
                  width: 84,
                  weight: 150,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 7,
    name: 'Harlequin 1300HQi',
    brand: 'Harlequin',
    price: 1318.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1300_2048x2048.jpg?v=1578346074',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1300_2048x2048.jpg?v=1578346074',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424802271298',
    physicalprops:   {volume: 1300,
                  brimfulVolume: 1344,
                  height: 154,
                  length: 211,
                  width: 95,
                  weight: 168,
                  shapeType: '',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 270 x 155 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 8,
    name: 'Harlequin 1400HQi',
    brand: 'Harlequin',
    price: 1366.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1400_2048x2048.jpg?v=1578345587',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1400_2048x2048.jpg?v=1578345587',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424798961730',
    physicalprops:   {volume: 1400,
                  brimfulVolume: 1452,
                  height: 142,
                  length: 190,
                  width: 125,
                  weight: 135,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 250 x 185 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 9,
    name: 'Harlequin 1450HQi',
    brand: 'Harlequin',
    price: 1110.00,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1450_2048x2048.jpg?v=1578346840',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_1450_2048x2048.jpg?v=1578346840',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424806891586',
    physicalprops:   {volume: 1450,
                  brimfulVolume: 1498,
                  height: 159,
                  length: 154,
                  width: 154,
                  weight: 112,
                  shapeType: '',
                  internalShape: 'vertical cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 214 x 214 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 10,
    name: 'Harlequin 2000HQi',
    brand: 'Harlequin',
    price: 1450.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_2000_2048x2048.jpg?v=1578347133',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_2000_2048x2048.jpg?v=1578347133',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424808628290',
    physicalprops:   {volume: 2000,
                  brimfulVolume: 2092,
                  height: 141.5,
                  length: 236,
                  width: 132,
                  weight: 180,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 296 x 192 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 11,
    name: 'Harlequin 2500HQi',
    brand: 'Harlequin',
    price: 1606.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_2500_2048x2048.jpg?v=1578347419',
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Harlequin_2500_2048x2048.jpg?v=1578347419',
    description: 'A large bunded tank',
    shopifyFlag: true,
    shopify_id: '4424810594370',
    physicalprops:   {volume: 2500,
                  brimfulVolume: 2571,
                  height: 147,
                  length: 246,
                  width: 143.5,
                  weight: 210,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Available as a tank-only HQi model, tank and tankpack ITE model, or top outlet ITT model',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 306 x 203.5 cm',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },
//End of Harlequin Tanks 

/*
  {
    tankId: 2,
    name: 'Titan Ecosafe ESB2500 Slimline',
    brand: 'Titan',    
    old: false,
    price: 1299,
    guarantee: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT.jpg?alt=media&token=0ad82400-2b9d-4537-9cc8-4ab9ab9733d2',
    image_thumb: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT_thumb.png?alt=media&token=2fdde85e-480d-4cdd-bbe4-81201d9c2715',
    shopifyFlag: true,
    shopify: 'N/A',
    shopify_id: '4408929124418',
    physicalprops:   {volume: 2500,
                      height: 130,
                      length: 150,
                      width: 1,
                      internalHeight: 109,
                      weight: 200,
                      shapeType: 'slimline',
                      internalShape: 'vertical cylinder',
                      material: 'plastic',
                      bunded: 'bunded', 
                      fuelType: 'Heating Oil, Diesel, Gas Oil '
                    },
    descriptionmain: {description: 'A large bunded tank',
                      topfill: 'Top outlet - Optional (special order - please contact us)', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Inner tank vent',
                      misc2: 'Moulded in handles for ease of lifting',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
            standardtype: 'tail lift',
            standardtime: '48 Hour',
            standardconditions: 'If ordered before 10:30am (Postcode exclusions apply to AB, BT, DD, DG, EH, FK, G, IV, KA, KW, KY, ML, PA, PH, TD & TR)',
            option1cost: '£25',
            option1type: 'tail lift',
            option1time: '24 Hour',
            option1conditions: 'If ordered before 10:30am (Postcode exclusions apply to AB, BT, DD, DG, EH, FK, G, IV, KA, KW, KY, ML, PA, PH, TD & TR)',
            option2cost: '',
            option2type: '',
            option2time: '',
            option2conditions: ''
          }
  },


  {
    tankId: 3,
    name: 'Deso H1235BT',
    brand: 'Deso',
    old: true,
    price: 799,
    guarantee: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT.jpg?alt=media&token=0ad82400-2b9d-4537-9cc8-4ab9ab9733d2',
    image_thumb: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT_thumb.png?alt=media&token=2fdde85e-480d-4cdd-bbe4-81201d9c2715',
    shopifyFlag: false,
    shopify: '',
    shopify_id: '',
    physicalprops:   {volume: 1235,
              height: 100,
              length: 120,
              width: 150,
              internalHeight: 89,
              weight: 350,
              shapeType: 'low profile',
              internalShape: 'horizontal cylinder',
              material: 'plastic',
              bunded: 'bunded', 
              fuelType: 'Heating Oil, Diesel, Gas Oil '
            },
    descriptionmain: {
                  description: 'A low-profile single-skinned tank',
                  topfill: 'Top outlet - Optional (special order - please contact us)', 
                  lid: '16" lockable lid', 
                  bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                  inspectioncap: '4" lockable inspection cap',
                  gauge: '',
                  monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                  misc1: 'Inner tank vent',
                  misc2: 'Moulded in handles for ease of lifting',
                  misc3: '',
                  misc4: '',
                  misc5: '',
                  misc6: ''
                  }

  },
*/


//Start Diamond Tanks
  {
    tankId: 12,
    name: 'Diamond 1000SSL',
    brand: 'Diamond',
    price: 1234.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1000SSL_2048x2048.png?v=1578322768',  
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1000SSL_2048x2048.png?v=1578322768',  
    description: 'A slimline bunded tank',
    shopifyFlag: true,
//    shopify: 'https://warmandsmart.myshopify.com/products/harlequin-hqi1800',  
//    shopifybuybutton: '',
    shopify_id: '4424566308930',
    physicalprops:   {volume: 1000,
                  brimfulVolume: 999,
                  height: 146.5,
                  length: 190,
                  width: 64,
                  internalHeight: 126,
                  weight: 125,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee - (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 13,
    name: 'Diamond 1400SSL',
    brand: 'Diamond',
    price: 1354.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1400SSL_2048x2048.png?v=1578323640',  
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1400SSL_2048x2048.png?v=1578323640',  
    description: 'A slimline bunded tank',
    shopifyFlag: true,
    shopify_id: '4424583577666',
    physicalprops:   {volume: 1400,
                  brimfulVolume: 1435,
                  height: 167,
                  length: 211,
                  width: 64,
                  internalHeight: 146,
                  weight: 200,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee - (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

  {
    tankId: 14,
    name: 'Diamond 1650HZB',
    brand: 'Diamond',
    price: 1282.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1650HSL_2048x2048.png?v=1578326083',  
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1650HSL_2048x2048.png?v=1578326083',  
    description: 'A high-quality bunded tank',
    shopifyFlag: true,
    shopify_id: '4424630173762',
    physicalprops:   {volume: 1650,
                  brimfulVolume: 1662,
                  height: 143,
                  length: 201,
                  width: 135,
                  internalHeight: 123,
                  weight: 150,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: '',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },

    {
    tankId: 15,
    name: 'Diamond 2700HZB',
    brand: 'Diamond',
    price: 1498.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_2700HZB.png?v=1578328148',  
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_2700HZB.png?v=1578328148',  
    description: 'A high-quality bunded tank',
    shopifyFlag: true,
    shopify_id: '4424642756674',
    physicalprops:   {volume: 2700,
                  brimfulVolume: 2796,
                  height: 165,
                  length: 239.5,
                  width: 172,
                  internalHeight: 145,
                  weight: 190,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: '',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              }
  },
// End Diamond Tanks


];