export const tanks = [
//Start of Harlequin Tanks 
/*  {
    tankId: 1,
    name: 'Harlequin 350ITE',
    slug: 'Harlequin-350ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 702,
    old: false,
    guarantee: 10,
    image: 'https://ergavanu.sirv.com/Images/Harlequin%20Tanks/Harlequin%20350.jpg',
    imagealt: 'Harlequin 350ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4394263314498',
    physicalprops:   {volume: 350,
                  brimfulVolume: '358',
                  height: 116,
                  length: 98,
                  width: 98,
                  weight: 45,
                  shapeType: '',
                  internalShape: 'vertical cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: '', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: 'Installation:  cement base 158 x 158 cm',
                      misc2: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: ''
               option2conditions: ''
              },
    seo:  {title: 'Harlequin 350 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 350, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 350ITE 350 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },*/

  {
    tankId: 2,
    name: 'Harlequin 650ITE',
    slug: 'Harlequin-650ITE-slimline-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1050.00,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_650_dglina.jpg',
    imagealt: 'Harlequin 650ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424748433474',
    physicalprops:   {volume: 650,
                  brimfulVolume: '673',
                  height: 133,
                  length: 171.5,
                  width: 67,
                  weight: 116,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil'
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Installation:  cement base 231.5 x 127 cm',
                      misc3: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '5 business days',
               standardconditions: '',
               option1cost: '',
               option1type: '',
               option1time: '',
               option1conditions: '',
               option2cost: '',
               option2type: '',
               option2time: '',
               option2conditions: ''
              },
    seo:  {title: 'Harlequin 650 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 650, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 650ITE 650 litre low profile bunded heating oil tank. 10 yr guarantee."
          }     ,
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }       
  },

  {
    tankId: 3,
    name: 'Harlequin 1000ITE',
    slug: 'Harlequin-1000ITE-slimline-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1230.00,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1000_cweu0t.jpg',
    imagealt: 'Harlequin 1000ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424767209538',
    physicalprops:   {volume: 1000,
                  brimfulVolume: 1055,
                  height: 142,
                  length: 215,
                  width: 69,
                  weight: 132,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 275 x 131 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1000 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1000, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1000ITE 1000 litre low profile bunded heating oil tank. 10 yr guarantee."
          } ,
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }
  },

  {
    tankId: 4,
    name: 'Harlequin 1100ITE',
    slug: 'Harlequin-1100ITE-slimline-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1254.00,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1100_bqgyye.jpg',
    imagealt: 'Harlequin 1100ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424772616258',
    physicalprops:   {volume: 1100,
                  brimfulVolume: 1097,
                  height: 159.5,
                  length: 188,
                  width: 89,
                  weight: 132,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 248 x 149 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1100 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1100, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1100ITE 1100 litre low profile bunded heating oil tank. 10 yr guarantee."
          } ,
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }
  },

    {
    tankId: 5,
    name: 'Harlequin 1200ITE',
    slug: 'Harlequin-1200ITE-low-profile-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1294.80,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1200_oumrwt.jpg',
    imagealt: 'Harlequin 1200ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424778383426',
    physicalprops:   {volume: 1200,
                  brimfulVolume: 1317,
                  height: 96,
                  length: 190,
                  width: 160,
                  weight: 130,
                  shapeType: 'low profile',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A small bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 250 x 220 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1200 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1200, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1200ITE 1200 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },

  {
    tankId: 6,
    name: 'Harlequin 1225ITE',
    slug: 'Harlequin-1225ITE-slimline-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1278.00,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1225_lnkw6m.jpg',
    imagealt: 'Harlequin 1225ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424791195714',
    physicalprops:   {volume: 1225,
                  brimfulVolume: 1248,
                  height: 152.5,
                  length: 211,
                  width: 84,
                  weight: 150,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1225 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1225, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1225ITE 1225 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },

    {
    tankId: 7,
    name: 'Harlequin 1300ITE',
    slug: 'Harlequin-1300ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1294.80,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1300_qbllgi.jpg',
    imagealt: 'Harlequin 1300ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424802271298',
    physicalprops:   {volume: 1300,
                  brimfulVolume: 1344,
                  height: 154,
                  length: 211,
                  width: 95,
                  weight: 168,
                  shapeType: '',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 270 x 155 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1300 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1300, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1300ITE 1300 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },

    {
    tankId: 8,
    name: 'Harlequin 1400ITE',
    slug: 'Harlequin-1400ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1426.80,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1400_q3cfle.jpg',
    imagealt: 'Harlequin 1400ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424798961730',
    physicalprops:   {volume: 1400,
                  brimfulVolume: 1452,
                  height: 142,
                  length: 190,
                  width: 125,
                  weight: 135,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 250 x 185 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1400 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1400, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1400ITE 1400 litre low profile bunded heating oil tank. 10 yr guarantee."

          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },

    {
    tankId: 9,
    name: 'Harlequin 1450ITE',
    slug: 'Harlequin-1450ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1162.80,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_1450_arp4qz.jpg',
    imagealt: 'Harlequin 1450ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424806891586',
    physicalprops:   {volume: 1450,
                  brimfulVolume: 1498,
                  height: 159,
                  length: 154,
                  width: 154,
                  weight: 112,
                  shapeType: '',
                  internalShape: 'vertical cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 214 x 214 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 1450 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 1450, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 1450ITE 1100 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }
  },

    {
    tankId: 10,
    name: 'Harlequin 2000ITE',
    slug: 'Harlequin-2000ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1482.00,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_2000_hazmyp.jpg',
    imagealt: 'Harlequin 2000ITE bunded domestic heating oil tank',
    description: 'A small bunded tank',
    shopifyFlag: true,
    shopify_id: '4424808628290',
    physicalprops:   {volume: 2000,
                  brimfulVolume: 2092,
                  height: 141.5,
                  length: 236,
                  width: 132,
                  weight: 180,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 296 x 192 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 2000 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 2000, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 2000ITE 2000 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
      promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        } 
  },

    {
    tankId: 11,
    name: 'Harlequin 2500ITE',
    slug: 'Harlequin-2500ITE-bunded-heating-oil-tank',
    brand: 'Harlequin',
    price: 1594.80,
    old: false,
    guarantee: 10,
    image: 'Harlequin/Harlequin_2500_htzps5.jpg',
    imagealt: 'Harlequin 2500ITE bunded domestic heating oil tank',
    description: 'A large bunded tank',
    shopifyFlag: true,
    shopify_id: '4424810594370',
    physicalprops:   {volume: 2500,
                  brimfulVolume: 2571,
                  height: 147,
                  length: 246,
                  width: 143.5,
                  weight: 210,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: 'Optional - contact us to order', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover for an electronic oil monitor',
                      misc1: '',
                      misc2: 'Inner tank vent',
                      misc3: 'Installation:  cement base 306 x 203.5 cm',
                      misc4: 'Available as a tank-only HQi model, tank, monitor and tankpack ITE model (this one), or top outlet ITT model.  If you require HQi or ITT please contact us to place your order',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Harlequin 2500 litre ITE Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, harlequin, 2500, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Harlequin 2500ITE 2500 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }
  },
//End of Harlequin Tanks 

//Start Diamond Tanks
  {
    tankId: 12,
    name: 'Diamond 1000SSL',
    slug: 'Diamond-1000SSL-slimline-bunded-heating-oil-tank',
    brand: 'Diamond',
    price: 1234.80,
    old: false,
    guarantee: 10,
    image: 'Diamond/Diamond_1000SSL_lpcggs.png',
    image_thumb: 'https://ergavanu.sirv.com/Images/Diamond%20Tanks/Diamond%201000SSL.PNG',
    image_thumb_85: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1000SSL-ipad85-thumb_600x.png?v=1580733413',
    image_thumb_55: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_1000SSL-iphone55-thumb_600x.png?v=1580733413',  
    imagealt: 'Diamond 1000SSL super slimline bunded domestic heating oil tank',
    description: 'A slimline bunded tank',
    shopifyFlag: true,
//    shopify: 'https://warmandsmart.myshopify.com/products/harlequin-hqi1800',  
//    shopifybuybutton: '',
    shopify_id: '4424566308930',
    physicalprops:   {volume: 1000,
                  brimfulVolume: 999,
                  height: 146.5,
                  length: 190,
                  width: 64,
                  internalHeight: 126,
                  weight: 125,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee - (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Diamond 1000 Litre SSL Super Slimline Bunded Oil Tank',
          keywords: 'oil tank, bunded, diamond, 1000, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Diamond 1000SSL 1000 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
        }
  },

  {
    tankId: 13,
    name: 'Diamond 1400SSL',
    slug: 'Diamond-1400SSL-slimline-bunded-heating-oil-tank',
    brand: 'Diamond',
    price: 1354.80,
    old: false,
    guarantee: 10,
    image: 'Diamond/Diamond_1400SSL_nzem1a.png',  
    imagealt: 'Diamond 1400SSL super slimline bunded domestic heating oil tank',
    description: 'A slimline bunded tank',
    shopifyFlag: true,
    shopify_id: '4424583577666',
    physicalprops:   {volume: 1400,
                  brimfulVolume: 1435,
                  height: 167,
                  length: 211,
                  width: 64,
                  internalHeight: 146,
                  weight: 200,
                  shapeType: 'slimline',
                  internalShape: 'cuboid',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: 'A slimline bunded tank',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee - (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Diamond 1400 Litre SSL Super Slimline Bunded Oil Tank',
          keywords: 'oil tank, bunded, diamond, 1400, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Diamond 1400SSL 1400 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
            }
  },

  {
    tankId: 14,
    name: 'Diamond 1650HZB',
    slug: 'Diamond-1650HZB-bunded-heating-oil-tank',
    brand: 'Diamond',
    price: 1282.80,
    old: false,
    guarantee: 10,
    image: 'Diamond/Diamond_1650HSL_ze0jqk.png',  
    imagealt: 'Diamond 1650HZB bunded domestic heating oil tank',
    description: 'A high-quality bunded tank',
    shopifyFlag: true,
    shopify_id: '4424630173762',
    physicalprops:   {volume: 1650,
                  brimfulVolume: 1662,
                  height: 143,
                  length: 201,
                  width: 135,
                  internalHeight: 123,
                  weight: 150,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: '',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '48 hours',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: '24 hours',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: 'Diamond 1650 Litre HZB Bunded Oil Tank | SmartNow',
          keywords: 'oil tank, bunded, diamond, 1650, CE-mark, 24 hour deliver, 48 hour delivery',
          description: "FREE 48 hour delivery, free oil monitor and free tank pack! The Diamond 1650HZB 1650 litre low profile bunded heating oil tank. 10 yr guarantee."
          },
    promo:   {include: true,
              image: "Accessories/Tankpack_jx9ow0.jpg",
              imagealt: "Tank pack including bottom outlet and Apollo oil monitor",
              header: "FREE tank bottom outlet kit and Apollo Ultrasonic oil monitor!",
              text: "The Apollo Ultrasonic monitors the level of fuel inside the tank and shows it on the display in your home, including a low level warning alert.  The tank outlet kit includes everything you need to connect your heating oil tank to the supply pipe"
            }
  }
];
/*    {
    tankId: 15,
    name: 'Diamond 2700HZB',
    slug: 'Diamond-2700HZB-bunded-heating-oil-tank',
    brand: 'Diamond',
    price: 1498.80,
    old: false,
    guarantee: 10,
    image: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_2700HZB.png?v=1578328148',  
    image_thumb: 'https://cdn.shopify.com/s/files/1/0258/2154/4514/products/Diamond_2700HZB.png?v=1578328148',  
    imagealt: 'Diamond 2700HZB bunded domestic heating oil tank',
    description: 'A high-quality bunded tank',
    shopifyFlag: true,
    shopify_id: '4424642756674',
    physicalprops:   {volume: 2700,
                  brimfulVolume: 2796,
                  height: 165,
                  length: 239.5,
                  width: 172,
                  internalHeight: 145,
                  weight: 190,
                  shapeType: '',
                  internalShape: 'horizontal cylinder',
                  material: 'plastic',
                  bunded: 'bunded', 
                  fuelType: 'Heating Oil, Diesel, Gas Oil '
                },
    descriptionmain: {description: '',
                      topfill: '', 
                      lid: 'Heavy duty lockable manhole access', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: 'Contents dipstick',
                      monitorpoint: '32mm mounting point (with cover) for fitting an electronic oil monitor',
                      misc1: 'Moulded in handles for ease of lifting',
                      misc2: 'Non-Corrosive, made from MDPE',
                      misc3: '10 year gaurantee (requires registration)',
                      misc4: 'Meets regulations - independently tested and approved to EN13341',
                      misc5: 'Made by Harlequin Tanks',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
               standardtype: 'tail lift',
               standardtime: '2 day (48 hours)',
               conditions: '24 / 48 hour delivery if order placed before 11am, excludes AB, BT, DD, EH, FK, G, HS, IV, KA, KW, KY, ML, PA & PH postcodes.  Delivery to curbside.  Days quoted are business days',
               option1cost: '£25',
               option1type: 'tail lift',
               option1time: 'Next day (24 hours)',
               option2cost: '',
               option2type: '',
               option2time: '',
              },
    seo:  {title: '2700 Litre Super Slimline Bunded Heating Oil Tank - Diamond 2700HZB | SmartNow Ltd | SmartNowUK.com'

          }
  },
  */
// End Diamond Tanks

/*
  {
    tankId: 2,
    name: 'Titan Ecosafe ESB2500 Slimline',
    brand: 'Titan',    
    old: false,
    price: 1299,
    guarantee: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT.jpg?alt=media&token=0ad82400-2b9d-4537-9cc8-4ab9ab9733d2',
    image_thumb: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT_thumb.png?alt=media&token=2fdde85e-480d-4cdd-bbe4-81201d9c2715',
    shopifyFlag: true,
    shopify: 'N/A',
    shopify_id: '4408929124418',
    physicalprops:   {volume: 2500,
                      height: 130,
                      length: 150,
                      width: 1,
                      internalHeight: 109,
                      weight: 200,
                      shapeType: 'slimline',
                      internalShape: 'vertical cylinder',
                      material: 'plastic',
                      bunded: 'bunded', 
                      fuelType: 'Heating Oil, Diesel, Gas Oil '
                    },
    descriptionmain: {description: 'A large bunded tank',
                      topfill: 'Top outlet - Optional (special order - please contact us)', 
                      lid: '16" lockable lid', 
                      bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                      inspectioncap: '4" lockable inspection cap',
                      gauge: '',
                      monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                      misc1: 'Inner tank vent',
                      misc2: 'Moulded in handles for ease of lifting',
                      misc3: '',
                      misc4: '',
                      misc5: '',
                      misc6: ''
                      },
    delivery: {standardcost: 'free',
            standardtype: 'tail lift',
            standardtime: '48 Hour',
            standardconditions: 'If ordered before 10:30am (Postcode exclusions apply to AB, BT, DD, DG, EH, FK, G, IV, KA, KW, KY, ML, PA, PH, TD & TR)',
            option1cost: '£25',
            option1type: 'tail lift',
            option1time: '24 Hour',
            option1conditions: 'If ordered before 10:30am (Postcode exclusions apply to AB, BT, DD, DG, EH, FK, G, IV, KA, KW, KY, ML, PA, PH, TD & TR)',
            option2cost: '',
            option2type: '',
            option2time: '',
            option2conditions: ''
          }
  },


  {
    tankId: 3,
    name: 'Deso H1235BT',
    brand: 'Deso',
    old: true,
    price: 799,
    guarantee: 10,
    image: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT.jpg?alt=media&token=0ad82400-2b9d-4537-9cc8-4ab9ab9733d2',
    image_thumb: 'https://firebasestorage.googleapis.com/v0/b/fir-demo-11999.appspot.com/o/Deso_H1235BT_thumb.png?alt=media&token=2fdde85e-480d-4cdd-bbe4-81201d9c2715',
    shopifyFlag: false,
    shopify: '',
    shopify_id: '',
    physicalprops:   {volume: 1235,
              height: 100,
              length: 120,
              width: 150,
              internalHeight: 89,
              weight: 350,
              shapeType: 'low profile',
              internalShape: 'horizontal cylinder',
              material: 'plastic',
              bunded: 'bunded', 
              fuelType: 'Heating Oil, Diesel, Gas Oil '
            },
    descriptionmain: {
                  description: 'A low-profile single-skinned tank',
                  topfill: 'Top outlet - Optional (special order - please contact us)', 
                  lid: '16" lockable lid', 
                  bottomfill: 'Bottom outlet with 1" BSP (F) thread',
                  inspectioncap: '4" lockable inspection cap',
                  gauge: '',
                  monitorpoint: '32mm hole with cover suitable for fitting an electronic oil monitor',
                  misc1: 'Inner tank vent',
                  misc2: 'Moulded in handles for ease of lifting',
                  misc3: '',
                  misc4: '',
                  misc5: '',
                  misc6: ''
                  }

  },
*/

